# Workflow to ensure whenever a GitHub PR is submitted,
# a JIRA ticket gets created automatically.
name: Create Jira Ticket from Pull Request

# Controls when the action will run.
on:
  pull_request_target:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-jira-ticket:
    name: Create Jira Ticket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
      - name: Create NEW JIRA ticket
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: CONUPDATE
          issuetype: Task
          summary: |
            GitHub PR nd081 - Azure Cloud Developer | Repo: ${{ github.repository }} | PR# ${{github.event.number}}
          description: |
            Repo link: https://github.com/${{ github.repository }}
            PR no. ${{ github.event.pull_request.number }}
            PR title: ${{ github.event.pull_request.title }}
            PR description: ${{ github.event.pull_request.description }}
            In addition, please resolve other issues, if any.
          fields: |
            {
              "components": [{"name":"nd081 - Azure Cloud Developer"}],
              "customfield_16449":"https://classroom.udacity.com/",
              "customfield_16450":"Resolve the PR",
              "labels": ["github"],
              "priority":{"id": "4"}
            }

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
